# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 02:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoria',
            new_name='category',
        ),
    ]
